[package]
name = "text-project"
version = "1.71.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quadtree_rs = "0.1.3"

